from datetime import datetime, timedelta
from html import escape
from uuid import uuid4

from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel, Field
from slugify import slugify

from ai_generator import generate_site
from storage import load_projects, save_projects, find_project_by_slug


app = FastAPI(title="HGGps Backend API")


app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class GenerateProjectRequest(BaseModel):
    description: str = Field(..., min_length=10)
    siteType: str = Field(default="Лендинг")
    goal: str = Field(default="Создать сайт")
    style: str = Field(default="Современный")


def make_unique_slug(site_name):
    projects = load_projects()

    base_slug = slugify(site_name) or "site"
    slug = base_slug
    counter = 1

    existing_slugs = {
        project.get("publicSlug")
        for project in projects
    }

    while slug in existing_slugs:
        slug = f"{base_slug}-{counter}"
        counter += 1

    return slug


def render_site_html(site_json):
    site_name = escape(site_json.get("siteName", "Сайт"))
    pages = site_json.get("pages", [])

    menu_html = ""
    content_html = ""

    for page in pages:
        page_title = escape(page.get("title", "Страница"))
        page_slug = page.get("slug", "/")
        anchor = page_slug.replace("/", "") or "home"

        menu_html += f'<a href="#{escape(anchor)}">{page_title}</a>'

        content_html += f'<section id="{escape(anchor)}" class="page-section">'
        content_html += f"<h2>{page_title}</h2>"

        sections = page.get("sections", [])

        for section in sections:
            section_type = section.get("type")

            if section_type == "hero":
                title = escape(section.get("title", ""))
                subtitle = escape(section.get("subtitle", ""))
                button_text = escape(section.get("buttonText", "Подробнее"))

                content_html += f"""
                <div class="hero-block">
                    <span class="badge">Generated by HGGps</span>
                    <h1>{title}</h1>
                    <p>{subtitle}</p>
                    <button>{button_text}</button>
                </div>
                """

            elif section_type == "features":
                title = escape(section.get("title", "Преимущества"))
                items = section.get("items", [])

                content_html += f"""
                <div class="card">
                    <h3>{title}</h3>
                    <div class="features-grid">
                """

                for item in items:
                    content_html += f"""
                    <div class="feature-item">
                        {escape(str(item))}
                    </div>
                    """

                content_html += """
                    </div>
                </div>
                """

            elif section_type == "text":
                title = escape(section.get("title", ""))
                description = escape(section.get("description", ""))

                content_html += f"""
                <div class="card">
                    <h3>{title}</h3>
                    <p>{description}</p>
                </div>
                """

            elif section_type == "contact":
                title = escape(section.get("title", "Контакты"))
                phone = escape(section.get("phone", ""))
                email = escape(section.get("email", ""))
                address = escape(section.get("address", ""))

                content_html += f"""
                <div class="card">
                    <h3>{title}</h3>
                    <p>Телефон: {phone}</p>
                    <p>Email: {email}</p>
                    <p>Адрес: {address}</p>
                </div>
                """

        content_html += "</section>"

    return f"""
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{site_name}</title>

    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}

        html {{
            scroll-behavior: smooth;
        }}

        body {{
            font-family: Arial, sans-serif;
            background: #0b0b10;
            color: #ffffff;
        }}

        header {{
            width: 100%;
            padding: 20px 8%;
            background: #12121a;
            border-bottom: 1px solid #2a2d3a;
            display: flex;
            align-items: center;
            justify-content: space-between;
            position: sticky;
            top: 0;
            z-index: 100;
        }}

        header strong {{
            color: #e11d2e;
            font-size: 24px;
        }}

        nav {{
            display: flex;
            gap: 18px;
            flex-wrap: wrap;
        }}

        nav a {{
            color: #b8bcc8;
            text-decoration: none;
            font-size: 15px;
        }}

        nav a:hover {{
            color: #e11d2e;
        }}

        .page-section {{
            padding: 60px 8%;
            max-width: 1200px;
            margin: 0 auto;
        }}

        .page-section h2 {{
            font-size: 34px;
            margin-bottom: 24px;
        }}

        .hero-block,
        .card {{
            background: #12121a;
            border: 1px solid #2a2d3a;
            border-radius: 24px;
            padding: 34px;
            margin-bottom: 24px;
            box-shadow: 0 18px 40px rgba(0, 0, 0, 0.35);
        }}

        .badge {{
            display: inline-block;
            padding: 8px 14px;
            background: rgba(225, 29, 46, 0.12);
            color: #e11d2e;
            border-radius: 999px;
            font-size: 14px;
            font-weight: 700;
            margin-bottom: 18px;
        }}

        .hero-block h1 {{
            font-size: 46px;
            line-height: 1.1;
            margin-bottom: 16px;
        }}

        .hero-block p,
        .card p,
        .feature-item {{
            color: #b8bcc8;
            line-height: 1.7;
            font-size: 16px;
        }}

        .hero-block button {{
            margin-top: 22px;
            padding: 14px 22px;
            border: none;
            border-radius: 14px;
            background: #e11d2e;
            color: white;
            font-weight: 700;
            cursor: pointer;
        }}

        .hero-block button:hover {{
            background: #b91523;
        }}

        .card h3 {{
            font-size: 24px;
            margin-bottom: 16px;
        }}

        .features-grid {{
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 14px;
        }}

        .feature-item {{
            background: #191923;
            border: 1px solid #2a2d3a;
            border-radius: 16px;
            padding: 18px;
        }}

        @media (max-width: 800px) {{
            header {{
                flex-direction: column;
                gap: 14px;
            }}

            nav {{
                justify-content: center;
            }}

            .hero-block h1 {{
                font-size: 34px;
            }}

            .features-grid {{
                grid-template-columns: 1fr;
            }}
        }}
    </style>
</head>

<body>
    <header>
        <strong>{site_name}</strong>
        <nav>
            {menu_html}
        </nav>
    </header>

    {content_html}
</body>
</html>
"""


@app.get("/")
def health_check():
    return {
        "status": "ok",
        "service": "HGGps Backend API",
        "message": "Backend работает"
    }


@app.post("/api/projects/generate")
def generate_project(data: GenerateProjectRequest, request: Request):
    site_json = generate_site(
        description=data.description,
        site_type=data.siteType,
        goal=data.goal,
        style=data.style
    )

    project_id = str(uuid4())
    slug = make_unique_slug(site_json.get("siteName", "site"))
    expires_at = datetime.now() + timedelta(days=7)

    base_url = str(request.base_url).rstrip("/")
    full_public_url = f"{base_url}/s/{slug}"

    project = {
        "id": project_id,
        "name": site_json.get("siteName", "Сайт"),
        "description": data.description,
        "siteType": data.siteType,
        "goal": data.goal,
        "style": data.style,
        "siteJson": site_json,
        "status": "temporary",
        "publicSlug": slug,
        "publicUrl": f"/s/{slug}",
        "fullPublicUrl": full_public_url,
        "createdAt": datetime.now().isoformat(),
        "expiresAt": expires_at.isoformat()
    }

    projects = load_projects()
    projects.append(project)
    save_projects(projects)

    return project


@app.get("/api/public/{slug}")
def get_public_site_json(slug: str):
    project = find_project_by_slug(slug)

    if not project:
        raise HTTPException(status_code=404, detail="Сайт не найден")

    expires_at = datetime.fromisoformat(project["expiresAt"])

    if datetime.now() > expires_at:
        raise HTTPException(status_code=410, detail="Временная ссылка истекла")

    return {
        "siteJson": project["siteJson"],
        "expiresAt": project["expiresAt"]
    }


@app.get("/s/{slug}", response_class=HTMLResponse)
def open_public_site(slug: str):
    project = find_project_by_slug(slug)

    if not project:
        raise HTTPException(status_code=404, detail="Сайт не найден")

    expires_at = datetime.fromisoformat(project["expiresAt"])

    if datetime.now() > expires_at:
        return HTMLResponse(
            content="<h1>Срок действия временной ссылки истёк</h1>",
            status_code=410
        )

    html = render_site_html(project["siteJson"])

    return HTMLResponse(content=html)
